---
title: "AZ Athenaeum - AAA"
author: "Marco Cora"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

```{r setup, include=FALSE, dev="svg"}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(pander)
label <- c("Conservative SAA", "Conservative TAA",
           "Diversified SAA", "Diversified TAA",
           "Growth SAA", "Growth TAA")
```








## AZ Athenaeum - Asset Class Weights
***


```{r SAA and TAA, results='asis'}


table.to.print <- rbind(
    cbind(Portfolio.Cons[[5]]$Weights[,1:2],
        Portfolio.Div[[5]]$Weights[,1:2],
        Portfolio.Grow[[5]]$Weights[,1:2]),
    colSums(cbind(Portfolio.Cons[[5]]$Weights[,1:2],
        Portfolio.Div[[5]]$Weights[,1:2],
        Portfolio.Grow[[5]]$Weights[,1:2]))
)

kable(table.to.print,
      col.names = label,
      digits = 2,
      align="cccccc",
      format = "pandoc",
      caption="SAA and TAA allocations")

```

<!-- 1. **General** -->
<!--     i) Increase in Risk -->
<!--     ii) Increase in Growth -->
<!--     iii) Reduction of Cash -->

<!-- 2. **Conservative** -->
<!--     i) Increase in AUS exposure both Equities and Fixed Income -->
<!--     ii) Increase in International Equities in particular EM and EU Equities -->
<!--     iii) Reduction in Global Fixed Income -->

<!-- 3. **Diversified** -->
<!--     i) Reduction of Non US, Non EU Developed Equities -->
<!--     ii) Increase in AUS Equities  -->
<!--     iv) Reduction in Global Fixed Income -->

<!-- 4. **Growth** -->
<!--     i) Shift in AUS exposure from FI to Equities  -->
<!--     ii) Increase in International Equities but a reduction in US Equities -->



## AZ Athenaeum - Weights

***

SAA

***

```{r SAA Weights Pies, fig.width=14, fig.height=6}

par(mfrow=c(1,3),
    cex=1.1)

pie(Portfolio.Cons[[5]]$Weights[,1], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Cons[[5]]$Weights[,1]), sep=" "), 
    main="Conservative")

pie(Portfolio.Div[[5]]$Weights[,1], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Div[[5]]$Weights[,1]), sep=" "), 
    main="Diversified")

pie(Portfolio.Grow[[5]]$Weights[,1], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Grow[[5]]$Weights[,1]), sep=" "), 
    main="Growth")


```


TAA

***

```{r TAA weight Pies, fig.width=14, fig.height=6}

par(mfrow=c(1,3),
    cex=1.1)

pie(Portfolio.Cons[[5]]$Weights[,2], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Cons[[5]]$Weights[,2]), sep=" "), 
    main="Conservative")

pie(Portfolio.Div[[5]]$Weights[,2], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Div[[5]]$Weights[,2]), sep=" "), 
    main="Diversified")

pie(Portfolio.Grow[[5]]$Weights[,2], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Grow[[5]]$Weights[,2]), sep=" "), 
    main="Growth")


```


## AZ Athenaeum - TAA Tilts
***

```{r TAA tilts, fig.height=12}

par(mfrow=c(3,1))

barplot(t(Portfolio.Cons[[5]]$Weights[,2]-Portfolio.Cons[[5]]$Weights[,1]),
        beside=TRUE,
        col=c("darkgreen"),
        legend.text=c("TAA tilt"),
        horiz=FALSE,
        names.arg=rownames(Portfolio.Div[[5]]$Weights),
        main="AZ Athenaeum - Conservative") 

barplot(t(Portfolio.Div[[5]]$Weights[,2]-Portfolio.Div[[5]]$Weights[,1]),
        beside=TRUE,
        col=c("darkblue"),
        legend.text=c("TAA tilt"),
        horiz=FALSE,
        names.arg=rownames(Portfolio.Div[[5]]$Weights),
        main="AZ Athenaeum - Diversified") 

barplot(t(Portfolio.Grow[[5]]$Weights[,2]-Portfolio.Grow[[5]]$Weights[,1]),
        beside=TRUE,
        col=c("firebrick"),
        legend.text=c("TAA tilt"),
        horiz=FALSE,
        names.arg=rownames(Portfolio.Div[[5]]$Weights),
        main="AZ Athenaeum - Growth") 

```



## AZ Athenaeum - Factor Contribution
***
SAA

***

```{r SAA Factor Contributions, fig.width=14, fig.height=5}

par(mfrow=c(1,3))

pie(Portfolio.Cons[[5]]$`Factor Contributions`[,1], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Cons[[5]]$`Factor Contributions`[,1]), sep=" "), 
    main="Conservative")

pie(Portfolio.Div[[5]]$`Factor Contributions`[,1],
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Div[[5]]$`Factor Contributions`[,1]), sep=" "), 
    main="Diversified")

pie(Portfolio.Grow[[5]]$`Factor Contributions`[,1],
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Grow[[5]]$`Factor Contributions`[,1]), sep=" "), 
    main="Growth")

```

TAA

***

```{r TAA Factor Contributions, fig.width=14, fig.height=5}

par(mfrow=c(1,3))

pie(Portfolio.Cons[[5]]$`Factor Contributions`[,2], 
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Cons[[5]]$`Factor Contributions`[,2]), sep=" "), 
    main="Conservative")

pie(Portfolio.Div[[5]]$`Factor Contributions`[,2],
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Div[[5]]$`Factor Contributions`[,2]), sep=" "), 
    main="Diversified")

pie(Portfolio.Grow[[5]]$`Factor Contributions`[,2],
    labels = paste(rownames(Portfolio.Div[[5]]$Weights),t(Portfolio.Grow[[5]]$`Factor Contributions`[,2]), sep=" "), 
    main="Growth")


```





## Appendix - Correlation
***

```{r Correlations}
library(corrplot)

corrplot.mixed (Cormat.SAA, 
          lower ="pie",
          upper = "number")

legend <- matrix(seq(1:NumOfAssets), ncol = 1)
row.names(legend) <- Securities.names

```

```{r}
kable(legend,
      col.names = "Asset Number",
      format = "html")

```


